export const demoCategories = [
  { id: "cat-new", name: "New arrivals", slug: "new-arrivals", description: "Freshly considered. Ready to become your favourites." },
  { id: "cat-women", name: "For her", slug: "women", description: "Easy layers and pieces with a little presence." },
  { id: "cat-men", name: "For him", slug: "men", description: "The everyday, edited down to what matters." },
  { id: "cat-essentials", name: "Essentials", slug: "essentials", description: "Quiet staples, made to earn their place." }
];

const sizes = ["XS", "S", "M", "L", "XL"];
const shirtVariants = (colors) => colors.flatMap(([name, value], ci) => sizes.map((size, si) => ({ id: `v-${ci}-${si}`, size, color: name, colorHex: value, stock: [5, 8, 7, 4, 3][si] })));
const jeansVariants = (colors) => colors.flatMap(([name, value], ci) => [28, 30, 32, 34, 36].map((size, si) => ({ id: `v-${ci}-${si}`, size: String(size), color: name, colorHex: value, stock: [4, 7, 9, 6, 3][si] })));
const palette = {
  ivory: ["Ivory", "#e9e2d4"], sand: ["Sand", "#c4aa87"], olive: ["Olive", "#68745b"], ink: ["Ink", "#303630"], sky: ["Sky", "#9eafbc"], rose: ["Dusty rose", "#bd9690"], denim: ["Washed denim", "#6e7e8a"], charcoal: ["Charcoal", "#505450"]
};

export const demoProducts = [
  { id: "lyv-001", slug: "the-weekend-shirt", name: "The Weekend Shirt", category: "For her", categorySlug: "women", price: 1890, compareAt: 2290, label: "Bestseller", image: "https://images.unsplash.com/photo-1752825609278-f9696bc9d7bd?auto=format&fit=crop&w=900&q=82", description: "A relaxed, airy cotton shirt for slow starts and long lunches. Cut with a softly dropped shoulder and just the right amount of room.", material: "100% breathable cotton", variants: shirtVariants([palette.ivory, palette.sky, palette.rose]), featured: true },
  { id: "lyv-002", slug: "everyday-overshirt", name: "Everyday Overshirt", category: "For him", categorySlug: "men", price: 2490, compareAt: 2990, label: "New", image: "https://images.unsplash.com/photo-1562004760-aceed7bb0fe3?auto=format&fit=crop&w=900&q=82", description: "A considered layer in brushed cotton twill. Wear it open over a tee or buttoned up on cooler evenings.", material: "98% cotton, 2% elastane", variants: shirtVariants([palette.sand, palette.olive, palette.ink]), featured: true },
  { id: "lyv-003", slug: "soft-form-tee", name: "Soft Form Tee", category: "Essentials", categorySlug: "essentials", price: 990, compareAt: null, label: "Core essential", image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=82", description: "A little more softness in your everyday. Midweight, pre-washed cotton with a relaxed shape that drapes just so.", material: "100% organic cotton", variants: shirtVariants([palette.ivory, palette.ink, palette.olive, palette.rose]), featured: true },
  { id: "lyv-004", slug: "easy-line-trouser", name: "Easy Line Trouser", category: "For her", categorySlug: "women", price: 2190, compareAt: null, label: "", image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=82", description: "A clean, easy leg with an elasticated back waist. Made for the days you want to feel put together without trying too hard.", material: "Cotton-linen blend", variants: jeansVariants([palette.sand, palette.ink]), featured: true },
  { id: "lyv-005", slug: "daily-polo", name: "Daily Polo", category: "For him", categorySlug: "men", price: 1790, compareAt: 2190, label: "Limited", image: "https://images.unsplash.com/photo-1775306413232-fecd45367613?auto=format&fit=crop&w=900&q=82", description: "A clean cotton polo with a softly structured collar and an easy shape for warmer days.", material: "Soft cotton piqué", variants: shirtVariants([palette.sky, palette.ink, palette.ivory]), featured: false },
  { id: "lyv-006", slug: "Sunday-layer", name: "Sunday Layer", category: "Essentials", categorySlug: "essentials", price: 2690, compareAt: null, label: "New", image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=82", description: "A lightweight knit to keep within reach. Soft ribbed details and a comfortable shape make it an all-season favourite.", material: "Cotton-modal blend", variants: shirtVariants([palette.sand, palette.rose, palette.sky]), featured: true },
  { id: "lyv-007", slug: "field-jacket", name: "Field Jacket", category: "For him", categorySlug: "men", price: 3290, compareAt: 3890, label: "Bestseller", image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=82", description: "A dependable outer layer with considered pockets and a clean, comfortable fit. Ready for the in-between weather.", material: "Washed cotton canvas", variants: shirtVariants([palette.olive, palette.sand]), featured: true },
  { id: "lyv-008", slug: "daylight-kurta", name: "Daylight Kurta", category: "For her", categorySlug: "women", price: 2390, compareAt: null, label: "", image: "https://images.unsplash.com/photo-1669199583223-41040360e0a1?auto=format&fit=crop&w=900&q=82", description: "An easy, everyday kurta in a joyful print. Light cotton and a relaxed shape carry you from the first coffee to the last plan.", material: "Printed cotton", variants: shirtVariants([palette.rose, palette.olive, palette.ink]), featured: false },
  { id: "lyv-009", slug: "straight-leg-denim", name: "Straight Leg Denim", category: "For him", categorySlug: "men", price: 2890, compareAt: null, label: "", image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=82", description: "A straight leg that sits naturally and gets better with every wear. Softened indigo denim with classic five-pocket details.", material: "99% cotton, 1% stretch", variants: jeansVariants([palette.denim, palette.ink]), featured: false },
  { id: "lyv-010", slug: "the-woven-shopper", name: "The Woven Shopper", category: "Essentials", categorySlug: "essentials", price: 1490, compareAt: null, label: "", image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=82", description: "A roomy woven shopper with sturdy handles for market mornings, travel days and everything in between.", material: "Woven raffia with leather trim", variants: [{ id: "v-one", size: "One size", color: "Natural", colorHex: "#c5ae8a", stock: 18 }] },
  { id: "lyv-011", slug: "soft-knit-cardigan", name: "Soft Knit Cardigan", category: "For her", categorySlug: "women", price: 2990, compareAt: 3490, label: "New", image: "https://images.unsplash.com/photo-1580247934869-c12922c4f6b0?auto=format&fit=crop&w=900&q=82", description: "A softly structured layer in a fine, touchable knit. Gently cropped so it works with almost everything you own.", material: "Cotton and recycled nylon", variants: shirtVariants([palette.sky, palette.ivory, palette.rose]), featured: true },
  { id: "lyv-012", slug: "clean-cut-chino", name: "Clean Cut Chino", category: "For him", categorySlug: "men", price: 2290, compareAt: null, label: "", image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=82", description: "An easy straight fit with a clean finish and a little stretch. Made for the daily rotation, whatever's in it.", material: "Cotton twill with stretch", variants: jeansVariants([palette.sand, palette.olive, palette.ink]), featured: false }
];

export const demoCoupons = {
  WELCOME10: { discount_type: "percent", discount_value: 10, min_order: 999, max_discount: 750 },
  STUDIO15: { discount_type: "percent", discount_value: 15, min_order: 2500, max_discount: 1000 }
};
